language: cpp
rvm: system

before_cache:
  - brew cleanup
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar/cvc4/1.6

matrix:
  include:
    # OS X Yosemite (not supported)
#    - os: osx
#      osx_image: xcode6.4
    # OS X El Capitan (not supported)
#    - os: osx
#      osx_image: xcode8
    # macOS Sierra
#    - os: osx
#      osx_image: xcode9.2
#     macOS High Sierra
    - os: osx
      osx_image: xcode10.1

before_install:
  - brew update
install:
#  - brew install cmake
#  - brew install boost
  - brew install libressl
  # Install yaml-cpp
  - git clone -q https://github.com/jbeder/yaml-cpp.git
  - mkdir yaml-cpp/build
  - cd yaml-cpp/build
  - cmake ..
  - make
  - make install
  - cd ../../
  - rm -rf yaml-cpp
  # Install cvc4
  - travis_wait 60 brew install cvc4/cvc4/cvc4
  - brew link cvc4/cvc4/cvc4
  # Install symfpu
  - pushd /usr/local/include
  - git clone -q https://github.com/martin-cs/symfpu.git -b CVC4
  - popd
script:
  - mkdir build
  - cd build
  - XCODE_VERSION=$(xcodebuild -version | head -n1 | cut -d ' ' -f 2) cmake ..
  - make install
  - poac --version

notifications:
  slack: poacpm:VNE7FkuxYAghHHrEfKaj2V19
