language: cpp

before_cache:
  - brew cleanup
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - libssl-dev
      - libgit2-dev
      - g++-8
      - libboost1.70-dev
  coverity_scan:
    project:
      name: poacpm/poac
      description: Package manager for C++
    build_command_prepend: >
      mkdir build &&
      cd build &&
      cmake -Dpoac_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Coverage ..
    build_command: make
    branch_pattern: coverity_scan
  homebrew:
    update: true
    packages:
      - openssl
      - libgit2
      - matken11235/toml11/toml11

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      if: branch = coverity_scan
      before_cache: ignore
      cache: false
      install: brew install matken11235/toml11/toml11
      script: echo
    # macOS High Sierra
    - os: osx
      osx_image: xcode10.1
      if: branch != coverity_scan
      install: brew install llvm@7
    # macOS Mojave
    - os: osx
      osx_image: xcode11.2
      if: branch != coverity_scan

script:
  - mkdir build
  - cd build
  - cmake -Dpoac_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make install
  - ctest --output-on-failure --verbose
  - poac help
  - cd ../

notifications:
  email: false
  slack:
    secure: "UQ2hUnwff1tpHrsoZK4lI+hIrH8SIIL++0rIK+zXSInw6BVo8XMVqZ9VHoZffb3pchqO8snHsAv6DE6L3BC4N74SrDMK0PGC87sdg5iZlH11qDaIxQRImEGBOysJH8taZsjq+AcBZahtpuXrahB9seCBFvb4nOvS4OzVpcLHSUtyfNm3ACuL9JgJbXFv6zyD5AiXslqfsNCQqxBmklY/TjEIM2Wtt3g8zvEUqgH0ZA/fyao4wiihgAJ2BY6vvuXU1edNybtHNeJfuxnY87Mo8+xod/4/lfL48wjnaZ1muycSqPi2II78QEm3eyMWPJIvims2MIkaOwaBUtBSYsxBL1XuuUsbP2jRDprY35DAbsDKtbPLn6YuFEAFumsNCbiiF5XSorgDqGvTSoXpPX2dtO/xSbJf3NEs4i2z9MyiZCpWPyQV0q00rubB4PSJK6o7HmuHEjN89a8gSOJLWQO2e0ah9zL0crrxezVxUn/d9AB2mwTP9YSoUwjuercN7KSf0ZBzfYEMnpkKTe1aK1kpqcGtYHa8sHrwGypNvBsaVphXhaisYYnPSIMsnDasbU0Q66x3LtCvkA7zvQrFlessVpszcYEAQ9XYvVb2e18hVGWpkrCVjkAHCuzMZ/JAV/T+cK/WMxbRx/JIvyMkMGemlREqGMYnvNpGkY1uwF/pqYM="
