language: cpp
rvm: system

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup

matrix:
  include:
    - os: osx
      osx_image: xcode6.4  # OS X Yosemite
    - os: osx
      osx_image: xcode8  # OS X El Capitan
    - os: osx
      osx_image: xcode9.2  # macOS Sierra
    - os: osx
      osx_image: xcode10.1  # macOS High Sierra

before_install:
  - brew update
#  - brew upgrade
install:
  - export PATH=/usr/local/opt/python/libexec/bin:$PATH
#  - brew install cmake
#  - brew install boost
  - brew install libressl
  - brew install yaml-cpp
  - travis_wait 60 brew install cvc4/cvc4/cvc4
script:
  - mkdir build
  - cd build
  - cmake ..
  - make install
  - poac --version

notifications:
  slack: poacpm:VNE7FkuxYAghHHrEfKaj2V19
