language: cpp
rvm: system

before_cache:
  - brew cleanup
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    # OS X El Capitan
    - os: osx
      osx_image: xcode8
      env: USE_DEFAULT_COMPILER=false
    # macOS Sierra
    - os: osx
      osx_image: xcode9.2
      env: USE_DEFAULT_COMPILER=false
    # macOS High Sierra
    - os: osx
      osx_image: xcode10.1
      env: USE_DEFAULT_COMPILER=true

before_install:
  - brew update
install:
  - | # Install llvm
    if [ "${USE_DEFAULT_COMPILER}" == "false" ]; then
      travis_wait 60 brew install llvm
      export CXX=/usr/local/opt/llvm/bin/clang++
      export LDFLAGS="-L/usr/local/opt/llvm/lib"
      export CPPFLAGS="-I/usr/local/opt/llvm/include"
    fi
  # Install yaml-cpp
  - git clone -q https://github.com/jbeder/yaml-cpp.git
  - mkdir yaml-cpp/build
  - cd yaml-cpp/build
  - cmake ..
  - make
  - make install
  - cd ../../
  - rm -rf yaml-cpp
script:
  - mkdir build
  - cd build
  - XCODE_VERSION=$(xcodebuild -version | head -n1 | cut -d ' ' -f 2) cmake ..
  - make install
  - poac -h

notifications:
  email: false
  slack:
    secure: "UQ2hUnwff1tpHrsoZK4lI+hIrH8SIIL++0rIK+zXSInw6BVo8XMVqZ9VHoZffb3pchqO8snHsAv6DE6L3BC4N74SrDMK0PGC87sdg5iZlH11qDaIxQRImEGBOysJH8taZsjq+AcBZahtpuXrahB9seCBFvb4nOvS4OzVpcLHSUtyfNm3ACuL9JgJbXFv6zyD5AiXslqfsNCQqxBmklY/TjEIM2Wtt3g8zvEUqgH0ZA/fyao4wiihgAJ2BY6vvuXU1edNybtHNeJfuxnY87Mo8+xod/4/lfL48wjnaZ1muycSqPi2II78QEm3eyMWPJIvims2MIkaOwaBUtBSYsxBL1XuuUsbP2jRDprY35DAbsDKtbPLn6YuFEAFumsNCbiiF5XSorgDqGvTSoXpPX2dtO/xSbJf3NEs4i2z9MyiZCpWPyQV0q00rubB4PSJK6o7HmuHEjN89a8gSOJLWQO2e0ah9zL0crrxezVxUn/d9AB2mwTP9YSoUwjuercN7KSf0ZBzfYEMnpkKTe1aK1kpqcGtYHa8sHrwGypNvBsaVphXhaisYYnPSIMsnDasbU0Q66x3LtCvkA7zvQrFlessVpszcYEAQ9XYvVb2e18hVGWpkrCVjkAHCuzMZ/JAV/T+cK/WMxbRx/JIvyMkMGemlREqGMYnvNpGkY1uwF/pqYM="
