[package]
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
description = "A package manager and build system for C++"
documentation = "https://docs.cabinpkg.com"
edition = "20"
homepage = "https://cabinpkg.com"
license = "Apache-2.0"
name = "cabin"
readme = "README.md"
repository = "https://github.com/cabinpkg/cabin"
version = "0.11.0"

[dependencies]
toml11 = {git = "https://github.com/ToruNiina/toml11.git", tag = "v4.2.0"}
fmt = {version = ">=8.1.1 && <12", system = true}
libcurl = {version = ">=7.79.1 && <9", system = true}
libgit2 = {version = ">=1.1.0 && <1.9", system = true}
nlohmann_json = {version = "3.10.5", system = true}
tbb = {version = ">=2021.5.0 && <2023.0.0", system = true}

[profile]
cxxflags = ["-pedantic-errors", "-Wall", "-Wextra", "-Wpedantic"]

[profile.release]
lto = true

[lint.cpplint]
filters = [
  "-build/c++11",
  "-build/c++17",
  "-build/include_order", # prioritize clang-format
  "-build/include_subdir",
  "-legal/copyright",
  "-readability/braces", # prioritize clang-format
  "-readability/nolint", # handle NOLINT comments for clang-tidy
  "-readability/todo",
  "-runtime/indentation_namespace", # inner namespace should be indented
  "-runtime/references", # non-const reference rather than a pointer
  "-whitespace",
  "+whitespace/ending_newline",
]
