[package]
name = "poac"
version = "0.3.0"
cpp = 17
authors = ["Ken Matsui <26405363+matken11235@users.noreply.github.com>"]
license = "GPL-3.0"
homepage = "https://poac.pm"
repository = "https://github.com/poacpm/poac"
description = "Poac is a package manager for C++"

[dependencies]
"matken11235/termcolor2" = ">=0.1.0 and <1.0.0"
#"matken11235/semver" = ">=0.1.0 and <1.0.0"
#"matken11235/git2-cpp" = ">=0.1.0 and <1.0.0"
#"matken11235/tar-cpp" = ">=0.1.0 and <1.0.0"
#"matken11235/url-cpp" = ">=0.1.0 and <1.0.0"
"poac-community/boost-predef" = ">=1.64.0 and <2.0.0"
#"poac-community/boost-property_tree" = ">=1.64.0 and <2.0.0"
#"poac-community/boost-filesystem" = { version = ">=1.64.0 and <2.0.0", link = "static" }
#"poac-community/boost-range" = ">=1.64.0 and <2.0.0"
#"poac-community/boost-algorithm" = ">=1.64.0 and <2.0.0"
#"poac-community/boost-foreach" = ">=1.64.0 and <2.0.0"
#"poac-community/boost-dynamic_bitset" = ">=1.64.0 and <2.0.0"
#"poac-community/boost-dll" = ">=1.64.0 and <2.0.0"
#"poac-community/boost-beast" = ">=1.64.0 and <2.0.0"
#"ToruNiina/toml11" = ">=3.0.0 and <4.0.0"

#[dev-dependencies]
#"poac-community/boost-test" = ">=1.64.0 and <2.0.0"

[target.'cfg(os = "linux")'.profile]
definitions = ["_GNU_SOURCE", "BOOST_ASIO_HAS_STD_STRING_VIEW"]

[target.'cfg(os = "unix")'.profile]
options = ["-fdiagnostics-color", "-Wall", "-Wextra", "-pthread"]
libraries = ["dl", "ssl", "crypt"]

[target.'cfg(os = "macos")'.profile]
include_directories = ["/usr/local/opt/openssl/include"]
link_directories = ["/usr/local/opt/openssl/lib"]

[target.'cfg(compiler = "msvc")'.profile]
definitions = ["BOOST_ASIO_HAS_STD_STRING_VIEW"]
options = ["/W4", "/bigobj"]

[target.'cfg(any(os = "cygwin", platform = "mingw"))'.profile]
options = ["-Wa,-mbig-obj"]

[target.'cfg(os = "windows")'.profile]
libraries = ["bcrypt", "ws2_32"]

[target.'cfg(os = "unix")'.profile.dev]
options = ["-fsanitize=address"]

[target.'cfg(os = "macos")'.profile.release]
options = ["-mtune=native", "-march=native"]

[target.'cfg(all(os = "macos", os_version < 14))'.profile]
compiler = "/usr/local/opt/llvm@7/bin/clang++"
include_directories = ["/usr/local/opt/llvm@7/include"]
link_directories = ["/usr/local/opt/llvm@7/lib"]

[profile]
libraries = ["boost_sysytem", "boost_filesystem", "git2"]

[profile.dev]
opt-level = "g"

[profile.release]
lto = true
