[package]
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
description = "A package manager and build system for C++"
documentation = "https://doc.poac.dev"
edition = 2020
homepage = "https://poac.dev"
license = "Apache-2.0"
name = "poac"
readme = "README.md"
repository = "https://github.com/poac-dev/poac"
version = "0.6.0"

[dependencies]
"ToruNiina/toml11" = {git = "https://github.com/ToruNiina/toml11.git", rev = "846abd9a49082fe51440aa07005c360f13a67bbf"}

[profile.release]
lto = true

[lint.cpplint]
filters = [
  "-legal/copyright",
  "-whitespace",
  "+whitespace/ending_newline",
  "-build/c++11",
  "-build/namespaces_literals", # Didn't work correctly with inline namespaces  # `namespace termcolor2::inline color_literals::inline foreground_literals`  # suggested to `namespace termcolor2::inline`
  "-readability/namespace", # Unknown NOLINT error category: bugprone-branch-clone  # This is for clang-tidy
  "-readability/nolint", # I believe non-const reference would be much better than a pointer.
  "-runtime/references",
]
