[package]
name = "poac" # required
version = "0.3.7" # required
edition = 2020 # required
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"] # required
license = "Apache-2.0" # required
homepage = "https://poac.pm"
repository = "https://github.com/poacpm/poac" # required
description = "Poac is a package manager for C++" # required

[dependencies]
"ken-matsui/termcolor2" = ">=0.1.0 and <1.0.0"
#"ken-matsui/semver" = ">=0.1.0 and <1.0.0"
#"ken-matsui/git2-cpp" = ">=0.1.0 and <1.0.0"
#"ken-matsui/tar-cpp" = ">=0.1.0 and <1.0.0"
#"ken-matsui/url-cpp" = ">=0.1.0 and <1.0.0"
"boost/predef" = ">=1.64.0 and <2.0.0"
#"boost/property_tree" = ">=1.64.0 and <2.0.0"
#"boost/range" = ">=1.64.0 and <2.0.0"
#"boost/algorithm" = ">=1.64.0 and <2.0.0"
#"boost/foreach" = ">=1.64.0 and <2.0.0"
#"boost/dynamic_bitset" = ">=1.64.0 and <2.0.0"
#"boost/beast" = ">=1.64.0 and <2.0.0"
#"ToruNiina/toml11" = ">=3.0.0 and <4.0.0"

#[dev-dependencies]
#"boost/test" = ">=1.64.0 and <2.0.0"

[target.'cfg(os = "linux")'.profile]
definitions = ["_GNU_SOURCE", "BOOST_ASIO_HAS_STD_STRING_VIEW"]

[target.'cfg(os = "unix")'.profile]
options = ["-fdiagnostics-color", "-Wall", "-Wextra", "-pthread"]
libraries = ["dl", "ssl", "crypt"]

[target.'cfg(os = "macos")'.profile]
include-directories = ["/usr/local/opt/openssl/include"]
link-directories = ["/usr/local/opt/openssl/lib"]

[target.'cfg(compiler = "msvc")'.profile]
definitions = ["BOOST_ASIO_HAS_STD_STRING_VIEW"]
options = ["/W4", "/bigobj"]

[target.'cfg(any(os = "cygwin", platform = "mingw"))'.profile]
options = ["-Wa,-mbig-obj"]

[target.'cfg(os = "windows")'.profile]
libraries = ["bcrypt", "ws2_32"]

[target.'cfg(os = "unix")'.profile.dev]
options = ["-fsanitize=address"]

[target.'cfg(os = "macos")'.profile.release]
options = ["-mtune=native", "-march=native"]

[target.'cfg(all(os = "macos", os_version < "10.15"))'.profile]
compiler = "/usr/local/opt/llvm@7/bin/clang++"
include-directories = ["/usr/local/opt/llvm@7/include"]
link-directories = ["/usr/local/opt/llvm@7/lib"]

[profile]
libraries = ["boost_sysytem", "git2"]

[profile.release]
lto = true
