[package]
authors = ["Ken Matsui <26405363+ken-matsui@users.noreply.github.com>"]
description = "A package manager and build system for C++"
documentation = "https://doc.poac.dev"
edition = "20"
homepage = "https://poac.dev"
license = "Apache-2.0"
name = "poac"
readme = "README.md"
repository = "https://github.com/poac-dev/poac"
version = "0.7.0"

[dependencies]
"ToruNiina/toml11" = {git = "https://github.com/ToruNiina/toml11.git", rev = "846abd9a49082fe51440aa07005c360f13a67bbf"}

[profile.release]
lto = true

[lint.cpplint]
filters = [
  "-legal/copyright",
  "-whitespace",
  "+whitespace/ending_newline",
  "-build/c++11",
  "-readability/nolint", # Unknown NOLINT error category: bugprone-branch-clone  # This is for clang-tidy
  "-runtime/references", # non-const reference rather than a pointer
  "-readability/braces", # prioritize clang-format
  "-build/include_order", # prioritize clang-format
  "-build/include_subdir",
  "-readability/todo",
]
