aliases:
  - &restore-poac-cache
    keys: # restores saved poac cache
      - v1-poac-cache-{{ checksum "poac.lock" }}
      - v1-poac-cache-{{ checksum "poac.yml" }}
      - v1-poac-cache-{{ .Branch }}
      - v1-poac-cache
  - &save-poac-cache1
    key: v1-poac-cache-{{ checksum "poac.lock" }}
    paths: "deps"
  - &save-poac-cache2
    key: v1-poac-cache-{{ checksum "poac.yml" }}
    paths: "deps"
  - &save-poac-cache3
    key: v1-poac-cache-{{ .Branch }}
    paths: "deps"
  - &save-poac-cache4
    key: v1-poac-cache
    paths: "deps"

  - &restore-poac-build-cache
    keys: # restores saved poac build cache
      - v1-build-cache-{{ .Branch }}
      - v1-build-cache
  - &save-poac-build-cache1
    key: v1-build-cache-{{ .Branch }}
    paths: "_build"
  - &save-poac-build-cache2
    key: v1-build-cache
    paths: "_build"

  - &at-current
    at: .

  - &build-project
    name: Build Project
    command: mkdir build && cd build && cmake .. && make

  - &run-poac-test
    name: Test Project
    command: >
      ./build/poac test --report --
      --output_format=XML
      --log_level=all
      --report_level=no
  - &store-poac-test-result
    path: _build/test/report

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

  - &defaults
    steps:
      - attach_workspace: *at-current

      - run: uname -sm
      - run: *build-project
      - run: file ./build/poac

      - run: *run-poac-test
      - store_test_results: *store-poac-test-result

version: 2
jobs:
  checkout_code:
    docker:
      - image: poacpm/poac
    steps:
      - checkout

      - restore_cache: *restore-poac-cache
      - run: poac install # source file only (not pre-build)
      - save_cache: *save-poac-cache1
      - save_cache: *save-poac-cache2
      - save_cache: *save-poac-cache3
      - save_cache: *save-poac-cache4

      - persist_to_workspace:
          root: .
          paths: .

  x86_64-unknown-linux-gnu_gcc-6:
    docker:
      - image: poacpm/x86_64-unknown-linux-gnu
    environment:
      CXX: g++-6
    <<: *defaults

  x86_64-unknown-linux-gnu_gcc-7:
    docker:
      - image: poacpm/x86_64-unknown-linux-gnu
    environment:
      CXX: g++-7
    <<: *defaults

  x86_64-unknown-linux-gnu_gcc-8:
    docker:
      - image: poacpm/x86_64-unknown-linux-gnu
    environment:
      CXX: g++-8
    working_directory: /tmp/workspace/x86_64-unknown-linux-gnu
    steps:
      - attach_workspace:
          at: /tmp/workspace/x86_64-unknown-linux-gnu

      - run: uname -sm
      - run: *build-project
      - run: file ./build/poac

      - run: *run-poac-test
      - store_test_results: *store-poac-test-result

      - persist_to_workspace:
          root: /tmp/workspace
          paths: x86_64-unknown-linux-gnu

  x86_64-unknown-linux-gnu_clang-6:
    docker:
      - image: poacpm/x86_64-unknown-linux-gnu
    environment:
      CXX: /home/linuxbrew/.linuxbrew/opt/llvm@6/bin/clang++
      LDFLAGS: "-L/home/linuxbrew/.linuxbrew/opt/llvm@6/lib"
      CPPFLAGS: "-I/home/linuxbrew/.linuxbrew/opt/llvm@6/include"
    <<: *defaults

#  x86_64-pc-windows-gnu_gcc-6:
#    docker:
#      - image: japaric/x86_64-pc-windows-gnu
#    environment:
#      CXX: x86_64-w64-mingw32-g++-posix
#    <<: *defaults
# sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
#  i686-pc-windows-gnu_gcc-6:
#    docker:
#      - image: japaric/i686-pc-windows-gnu
#    environment:
#      CXX: i686-w64-mingw32-g++-posix
#    <<: *defaults

  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - attach_workspace:
          at: .
      - run: ls -a
      - run: go get github.com/tcnksm/ghr
#      - run: ghr 0.0.1 out

  gh_pages:
    working_directory: ~/poac/docs
    docker:
      - image: node:10
    steps:
      - checkout
      - run: git config --global user.name $USERNAME
      - run: git config --global user.email $EMAIL
      - run: cp -r .circleci docs
      - run: cd docs && npm i
      - run: cd docs && npm run build
      - run: cd docs && npm run publish

workflows:
  version: 2
  builds:
    jobs:
      - checkout_code:
          filters: *filter-ignore-gh-pages
      - x86_64-unknown-linux-gnu_gcc-6:
          filters: *filter-ignore-gh-pages
          requires:
            - checkout_code
      - x86_64-unknown-linux-gnu_gcc-7:
          filters: *filter-ignore-gh-pages
          requires:
            - checkout_code
      - x86_64-unknown-linux-gnu_gcc-8:
          filters: *filter-ignore-gh-pages
          requires:
            - checkout_code
      - x86_64-unknown-linux-gnu_clang-6:
          filters: *filter-ignore-gh-pages
          requires:
            - checkout_code
      - release:
          filters: *filter-ignore-gh-pages
          requires:
            - x86_64-unknown-linux-gnu_gcc-6
            - x86_64-unknown-linux-gnu_gcc-7
            - x86_64-unknown-linux-gnu_gcc-8
            - x86_64-unknown-linux-gnu_clang-6
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^[0-9]+(\.[0-9]+){2}.*$/
      - gh_pages:
          filters: *filter-ignore-gh-pages
