version: 2
jobs:
  gcc_7:
    docker:
      - image: matken11235/gcc-cmake-boost:gcc-7
    steps:
      - checkout
      - run: cmake .
      - run: make
      - run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
      - run: ./poac --help
  gcc_8:
    docker:
      - image: matken11235/gcc-cmake-boost:gcc-8
    steps:
      - checkout
      - run: cmake .
      - run: make
      - run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
      - run: ./poac --help

workflows:
  version: 2
  build_and_test:
    jobs:
      # GCC
      - gcc_7
      - gcc_8

