name: Slack Cleaner (Monthly)

on: push
#  schedule:
#    - cron:  '0 0 1 * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: matken11235/slack-cleaner@v1
        with:
          token: ${{ secrets.SLACK_LEGACY_TOKEN }}
          rate: '1'
          message: true
          channel: 'notifications'
          user: '*'
          before: "$(date -v -1m '+%Y%m%d')"
          perform: true

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*${{ github.workflow }} / clean*'
          url: ${{ secrets.SLACK_WEBHOOK }}
          username: 'GitHub Notification'
